sudo: required

services:
  - docker

language: go

go:
  - 1.11

env:
  - GO111MODULE=on

git:
  depth: false
  submodules: false

before_script:
  - go get -u github.com/astrocorp42/rocket
  - make test
  - make

script:
  - make all


deploy:
  provider: script
  script: make deploy

notifications:
  email:
    on_success: never
