sudo: false

language: go

go:
  - 1.11

env:
  - GO111MODULE=on

git:
  depth: false
  submodules: false

before_script:
  - go get -u github.com/astrocorp42/rocket
  - cd api && go get && cd ..

script:
  - make api

deploy:
  provider: script
  script: make deploy_api

notifications:
  email:
    on_success: never
